[".zsh/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"
[".zsh/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"
[".zsh/plugins/zsh-history-substring-search"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-history-substring-search.git"
refreshPeriod = "168h"
