# Migrated from atuin dotfiles (deprecated). See:
# https://docs.atuin.sh/ -> dotfiles/aliases is legacy and no longer synced.
alias at='atuin'
alias atsr='atuin scripts run'
alias chezmoi-backup='chezmoi managed -0 | xargs -0 tar czf chezmoi-backup-$(date -Iseconds).tar.gz'
alias claude-code='claude'
alias dc='docker compose'
alias dcrm='dc rm --force --stop'
alias dcupd='docker compose up --detach'
alias gitp='git push -u origin "$(git branch --show-current)"'
alias grep='grep --color=auto'
alias k='kubectl'
alias ll='ls -lah'
alias ls='ls --color=auto'
alias mvv='mv -v'
alias powershell='pwsh'
alias t='task'
alias tf='terraform'
alias tg='terragrunt'
alias tga='tg apply'
alias tgd='tg destroy'
alias tgp='tg plan'
alias tgr='tg refresh'
