#!/usr/bin/env bash
# TODO: Extract to template
# Lima BEGIN
# Make sure iptables and mount.fuse3 are available
PATH="${PATH}:/usr/sbin:/sbin"
export PATH
# Lima END

HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
XTERM='xterm-256color'

bindkey -e # Use vi keybindings even if our EDITOR is set to vi
setopt histignorealldups sharehistory interactivecomments

#region zsh plugins
plugins="${HOME}/.zsh/plugins"
for repo in \
    "zsh-syntax-highlighting" \
    "zsh-autosuggestions" \
    "zsh-history-substring-search"; do
    # shellcheck disable=SC1090
    source "${plugins}/${repo}/${repo}.zsh"
done
#endregion zsh plugins

# shellcheck disable=SC2206
fpath=("${HOME}/.zsh/fpath" ${fpath})
autoload -Uz compinit zmv
compinit

#region Oh-my-posh
arch=$(uname -m)
case "${arch}" in
    'aarch64') bitness='arm64' ;;
    'arm64') bitness='arm64' ;;

    'x86_64') bitness='64bit' ;;

    'i386') bitness='32bit' ;;
    *) bitness='arm32' ;;
esac

eval "$(atuin init zsh --disable-up-arrow || true)"
eval "$(mise activate zsh || true)"

#shellcheck disable=SC2154
export __SHELL_INFORMATION_POSH_258__="zsh@${ZSH_VERSION}@${bitness}"
eval "$(oh-my-posh init zsh --print --config "${HOME}/.support/omp.yml" || true)"
enable_poshtransientprompt
#endregion Oh-my-posh
