[settings]
lockfile = true
experimental = true

[tools]
"aqua:JanDeDobbeleer/oh-my-posh" = "29.8.0"
"aqua:amir20/dtop" = "0.6.13"
"aqua:entireio/cli" = "0.5.0"
"aqua:loft-sh/devpod" = "0.7.0-alpha.34"
"aqua:muquit/mailsend-go" = "1.0.10"
"aqua:schollz/croc" = "10.4.2"
"aqua:sibprogrammer/xq" = "1.4.0"
"aqua:zyedidia/micro" = "2.0.15"
aws = { version = "2.34.8", symlink_bins = "true" }
aws-vault = "7.9.10"
bitwarden = "2026.2.0"
cosign = "3.0.5"
doggo = "1.1.4"
fd = "10.4.2"
gh = "2.88.1"
jq = "1.8.1"
jujutsu = "0.39.0"
lazygit = "0.60.0"
minisign = "0.12"
oxker = "0.13.0"
powershell = "7.5.5"
rclone = "1.73.2"
ripgrep = "15.1.0"
shellcheck = "0.11.0"
sops = "3.12.1"
step = "0.29.0"
task = "3.49.1"
usql = "0.21.1"
xh = "0.25.3"
yq = "4.52.4"
