[settings]
lockfile = true
experimental = true

[tools]
"aqua:JanDeDobbeleer/oh-my-posh" = "31.1.2"
"aqua:ismaelgv/rnr" = "0.5.1"
"aqua:muquit/mailsend-go" = "1.0.12"
"aqua:schollz/croc" = "11.3.6"
"aqua:sibprogrammer/xq" = "1.5.1"
"aqua:zyedidia/micro" = "2.0.15"
doggo = "1.4.0"
fd = "10.5.0"
gh = "2.99.0"
jq = "1.8.2"
jujutsu = "0.44.0"
lazygit = "0.64.1"
node = "26.8.1"
powershell = "7.6.5"
rclone = "1.75.0"
ripgrep = "15.2.0"
shellcheck = "0.11.0"
task = "3.53.1"
usql = "0.21.4"
uv = "0.12.9"
xh = "0.26.2"
yq = "4.53.6"
